version: "3.1"

services:
    www:
        container_name: www
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
            - ./apache/sites-available:/etc/apache2/sites-available
            - ./apache/log:/var/log/apache2
            - ./apache/php:/etc/php/
        links:
            - db
        networks:
            - accellog
    db:
        container_name: mysqldb
        image: mysql:5.7
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=32505856
        environment:
            MYSQL_ROOT_PASSWORD: mudar
            MYSQL_DATABASE: accellog_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: mudar
        restart: always
        volumes:
            - ./data/persistent:/var/lib/mysql
        networks:
            - accellog

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        networks:
            - accellog
        environment:
            MYSQL_ROOT_PASSWORD: mudar

networks:
    accellog:
        driver: bridge

# https://hub.docker.com/_/mysql
# https://github.com/jcavat/docker-lamp/blob/master/docker-compose.yml
# https://hub.docker.com/r/phpmyadmin/phpmyadmin/
# https://hub.docker.com/_/mariadb